# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 630ac6b6af3c742e5e0c6cc44c5ca6c95a2d4f53f1f2b59a7f3b9ff90dfbe594baa906ce16e6b3446b2039be6b862bb2a460f7d12915eda2afc03052c75907e6

test:
  secret_key_base: 9825054f8a23c61a69d3bee6d7e688863098570064c1621a4d520c258f521b85dd75be7d33f101bfff947651316fa6ca156eff019e2f01ad37f11fb49d40eec9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
